services:
  postgres:
    image: postgres:16
    container_name: sales_pipeline_postgres
    environment:
      POSTGRES_DB: name_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d name_database"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
